spring:
  application:
    name: authentication-service
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${CLIENT_ID:}
            clientSecret: ${CLIENT_SECRET:}
            clientName: ${CLIENT_NAME:}